### ISSUE TITLE
Players have the gridref, how to I remove it from them?

### ISSUE THREAD

**Issue by mer8771** [DarthRogue/Status_Bar#1]
I don't want to call this a bug, but as the title said, how would I do this? BTW, Great mod! It's ok that my Admin's have it but it's like gps for the players and I don't want them to have this.
closed #1

**Comment by ravmustang** [comment]
Hey Mer, inside the main sqf are the listings

Player bar. SQF
you need to remove the grid on line 181.
That will remove the grid from the status bar that displays.

Otherwise if you want to remove it from the script itself.
You can remove lines 54, 55, 56 if you never plan on adding it back in.
That's just the variables, then remove line 181 and 198 and adjust the %number variables for the bar to reflect the changes you made to the var order.

Honestly just stick with the first option till you gain more knowledge on sqf scripting

**Comment by mer8771** [comment]
Perfect. Thank you for the help.

**Comment by ravmustang** [comment]
No problem, pay it forward when that time comes :)

Close it out Darth!

**Comment by DarthRogue** [comment]
Thanks!
